@startuml VetHotel

class HotelManager{
    - _hotel: Hotel
    - _file: String

    ' Hotel management
    + createHotel(): void
    + loadHotel(file: String): void
    + saveHotel(): void

    ' Main Menu
    + progressSeason(): SeasonType
    + satisfaction(): int
}

class Hotel{
    - _habitats: Map<String, Habitat>
    - _workers: Map<String, Worker>
    - _species: Map<String, Species>
    - _animals: Map<String, Animal>
    - _vaccines: Map<String, Vaccine>
    - _vaccineRegistry: VaccineRegistry[]
    - _trees: Map<String, Tree>

    ' Check how to notify tree listeners.
    - _season: SeasonType

    ' Main Menu called from HotelManager._hotel.command()
    + progressSeason(): SeasonType
    + satisfaction(): int

    ' Secondary Menus 4.2
    + animals(): Animal[]
    + addAnimal(id: String, name: Name, idSpecies: String, idHabitat: String): Animal
    + transferAnimal(idAnimal: String, idHabitat: String): void
    + animalSatisfaction(id: String): int

    ' Secondary Menus 4.3
    + workers(): Worker[]
    + addWorker(id: String, name: String, type: String): void
    + addResponsibilityToWorker(idWorker: String, idResponsibility: String): void
    + removeResponsibilityFromWorker(idWorker: String, idResponsibility: String): void
    + workerSatisfaction(id: String): int

    ' Secondary Menus 4.4
    + habitats(): Habitat[]
    + addHabitat(id: String, name: String, area: int): void
    + changeHabitatArea(id: String, area: int): void

    ' Devo meter influencia como o meu enum? e ter um if
    ' que decide qual enum significa a string na parte de execução
    ' do comando? ou aqui dentro.
    + changeHabitatSuitability(id: String, idSpecies: String, influence: String): void
    + addTreeToHabitat(idHabitat: String, idTree: String, name: String, age: int, cleanDiff: int, treeType: String): void
    + habitatTrees(id: String): Tree[]
    
    ' Secondary Menus 4.5
    + vaccines(): Vaccine[]
    + addVaccine(id: String, name: Name, idSpecies: String): void
    + vaccinateAnimal(idAnimal: String, idVaccine: String, idVet: String): void
    + vaccineRegistry(): VaccineRegistry[]

    ' Secondary Menus 4.6
    + habitatAnimals(id: String): Animal[]
    + animalVaccines(id: String): VaccineRegistry[]
    + vetVaccines(id: String): VaccineRegistry[]
    + filterWrongVaccinations(): VaccineRegistry[]  

    ' Searches
    + animalExistsException(id: String): Exception
    + animalExists(id: String): Animal
    + speciesExistsException(id: String): Exception
    + speciesExists(id: String): Species
    + workerExistsException(id: String): Exception
    + workerExists(id: String): Worker
    + habitatExistsException(id: String): Exception
    + habitatExists(id: String): Worker
    + treeExistsException(id: String): Exception
    + treeExists(id: String): Tree
    + vaccineExistsException(id: String): Exception
    + vaccineExists(id: String): Vaccine
}

class Animal{
    - {final} _id: String
    - {final} _name: String
    - {final} _species: Specie
    - _vaccineRegistry: VaccineRegistry[]
    - _habitat: Habitat

    + Animal(id: String, name: String, species: Species, habitat: Habitat)
    
    + transferAnimal(habitat: Habitat): void
    + satisfaction(): int
    + addVaccineRegistry(vaccineReg: VaccineRegistry): void
    + vaccineRegistry(): VaccineRegistry[]

    + toString(): String
    + equals(animal: Animal): boolean
    + hashCode(): int
}

class Species{
    - {final} _id: String
    - {final} _name: String
    - _animals: Map<String, Animal>
    - _vets: Map<String, Vet>

    + Species(id: String, name: String)
    
    + id(): String
    + addAnimal(animal: Animal): void
    + addVet(vet: Vet): void
    + removeVet(vet: Vet): void
    + animalCount(): int
    + vetCount(): int

    + equals(species: Species): boolean
    + hashCode(): int
}

class Habitat{
    - {final} _id: String
    - {final} _name: String
    - _area: int
    - _animals: Map<Species, Map<String, Animal>>
    - _suitability: Map<Species, Influence>
    - _careTakers: Map<String, CareTakers>
    - _trees: Map<String, Tree>

    + id(): String
    + addAnimal(animal: Animal): void
    + removeAnimal(animal: Animal): void
    + animals(): animals[]
    + sameSpeciesCount(species: Species): int
    + speciesSuitability(species: Species): Influence
    + area(): int
    + addCareTaker(careTaker: CareTaker): void
    + removeCareTaker(careTaker: CareTaker): void
    + careTakerCount(): int
    + calculateWork(): int
    + trees(): Tree[]
    + setArea(area: int): void
    + changeSuitability(species: Species, suitability: Influence): void
    + addTree(tree: Tree): void

    + equals(habitat: Habitat): boolean
    + hashCode(): int
    + toString(): String
}

abstract class Worker{
    - {final} _id: String
    - {final} _name: String
    - {final} _hotel: Hotel

    + Worker(id: String, name: String, hotel: Hotel)

    + id(): String
    # name(): String
    # hotel(): Hotel

    
    + abstract addResponsibility(id: String): void
    + abstract removeResponsibility(id: String): void
    + abstract satisfaction(): int

    + equals(worker: Worker): boolean
    + hashCode(): int
    + abstract toString(): String
}

class CareTaker extends Worker{
    - _responsibilities: Map<String, Habitat>

    + CareTaker(id: String, name: String, hotel: Hotel)
    
    + addResponsibility(id: String): void
    + removeResponsibility(id: String): void
    + satisfaction(): int

    + toString(): String
}

class Vet extends Worker{
    - _responsibilities: Map<String, Species>
    - _vaccineRegistry: VaccineRegistry[]

    + Vet(id: String, name: String, hotel: Hotel)
    
    + addResponsibility(id: String): void
    + removeResponsibility(id: String): void
    + satisfaction(): int
    + vaccinate(animal: Animal, vaccine: Vaccine): VaccineRegistry
    - calculateVaccineDamage(animal: Animal, vaccine: Vaccine): VaccineDamage
    - addVaccineRegistry(vaccineReg: VaccineRegistry): void
    + vaccineRegistry(): VaccineRegistry[]

    + toString(): String
}

Class Tree{
    - {final} _id: String
    - {final} _name: String
    - _age: int
    - {final} _birthSeason: SeasonType
    - {final} _cleanDifficulty: int
    - {final} _hotel: Hotel

    + Tree(id: String, name: String, age: int, birthSeason: SeasonType, cleanDiff: int, hotel: Hotel)
    
    + id(): String
    # name(): String
    # age(): int
    # cleanDifficulty(): int
    # hotel(): Hotel
    + totalCleaningEffort(): int

    - abstract seasonalEffort(): int 
    - abstract leaftState(): LeafState
    
    + equals(tree: Tree): boolean
    + hashCode(): int
    + abstract toString(): String
}

Class Evergreen extends Tree{
    + Evergreen(id: String, name: String, age: int, birthSeason: SeasonType, cleanDiff: int, hotel: Hotel)
    
    - seasonalEffort(): int
    - leaftState(): LeafState

    + toString(): String
}

Class Deciduous extends Tree{
    + Deciduous(id: String, name: String, age: int, birthSeason: SeasonType, cleanDiff: int, hotel: Hotel)
    
    - seasonalEffort(): int
    - leaftState(): LeafState

    + toString(): String
}

Class Vaccine {
    - {final} _id: String
    - {final} _name: String
    - _applyCount: int
    - _species: Map<String, Species>
 
    + Vaccine(id: String, name: String, species: Species[])
    
    + apply(): void

    + toString(): String
    + equals(vaccine: Vaccine): boolean
    + hashCode(): int
}

Class VaccineRegistry{
    - _vaccine: Vaccine
    - _vet: Vet
    - _species: Species
    - _animal: Animal
    - _vaccineDamage: VaccineDamage

    + VaccineRegistry(vaccine: Vaccine, vet: Vet, species: Species, animal: Animal, vaccineDamage: VaccineDamage)
    
    + vaccineDamage(): VaccineDamage
    
    + toString(): String
}

' Enums
enum VaccineDamage {
    NORMAL
    CONFUSION
    ACCIDENT
    ERROR
}

enum SeasonType {
    SPRING = 1
    SUMMER = 2
    FALL = 3
    WINTER = 4

    +next(): SeasonType
}

enum LeafState {
    WITHOUTLEAFS
    WITHLEAFS
    FALLINGLEAFS
    GENERATELEAVES
}

enum Influence{
    POS = 20
    NEG = 0
    NEU = -20
}

@enduml