@startuml Name

' + -> public
' - -> private
' # -> protected
' ~ -> package
' underlined -> static (represented by {static} as prefix )
' final -> represented by a {final} as prefix
' composição -> losangulo cheio
' agregação -> losangulo vazio
' associação -> linha
' dependência -> linha traçada

' Define classes
class Name {
    - _variable: Type
    + constructor(varible: type)
    + method(variable: type): type
}


@enduml