@startuml Name

' + -> public
' - -> private
' # -> protected
' ~ -> package
' {static} -> shared added as a prefix
' {final} -> constant added as prefix
' *-- -> composition full tilted square
' o-- -> agregation empty tilter square
' -- -> association line
' ..> -> dependency dotted line

' Define classes
class Name {
    - _variable: Type
    + constructor(varible: type)
    + method(variable: type): type
}


@enduml